{
    "openapi": "3.0.0",
    "info": {
        "description": "Flask App Email Scheduler",
        "version": "1.0.0",
        "title": "Flask App"
    },
    "paths": {
        "/save_email":{
            "post":{
                "tags":["MAIN FUNCTION"],
                "summary": "Create Email Event",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "title": "CreateEmailEvent",
                                "type": "object",
                                "properties": {
                                    "event_id":{
                                        "title": "event_id",
                                        "type": "integer",
                                        "minimum": 1
                                    },
                                    "email_subject":{
                                        "title": "email_subject",
                                        "type": "string"
                                    },
                                    "email_content":{
                                        "title": "email_content",
                                        "type": "string"
                                    },
                                    "timestamp":{
                                        "title": "timestamp",
                                        "type": "string"
                                    }
                                },
                                "required": ["event_id", "email_subject", "email_content", "timestamp"]
                            },
                            "example":{
                                "event_id": 1,
                                "email_subject": "string",
                                "email_content": "string",
                                "timestamp": "2022-02-25T20:15:10"
                            }
                        }
                    },
                    "required": true
                },
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{}
                        }}
                    }
                }
            }
        },
        "/email":{
            "get":{
                "tags":["Email"],
                "summary": "Get Email",
                "parameters": [
                    {
                        "required": false,
                        "schema": {
                            "title": "ID",
                            "type": "string",
                            "default": null
                        },
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Show the selected column, leave it empty to show all",
                        "schema": {
                            "title": "Fields",
                            "type": "string"
                        },
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "schema": {
                            "title": "Page",
                            "minimum": 1,
                            "type": "integer",
                            "default": 1
                        },
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Data limit in 1 page",
                        "schema": {
                            "title": "Limit",
                            "maximum": 100,
                            "exclusiveMinimum": false,
                            "type": "integer",
                            "default": 20
                        },
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Sort by available column",
                        "schema": {
                            "title": "Sortby",
                            "type": "string",
                            "default": "id"
                        },
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Sort the query: `asc` or `desc`",
                        "schema": {
                            "title": "SortType",
                            "type": "string",
                            "default": "asc"
                        },
                        "name": "sortType",
                        "in": "query"
                    }
                ],
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{},
                            "example":{
                                "data": {
                                  "list": [
                                    {
                                      "email_content": "Hello friend!\n\nThis event gonna be fun\n\ncheers!\nJoy",
                                      "email_sender": "joy.choco.banana@gmail.com",
                                      "email_subject": "Monthly Gathering Announcement",
                                      "id": 1,
                                      "sent": false,
                                      "timestamp": "Wed, 02 Mar 2022 23:40:44 GMT"
                                    }
                                  ]
                                },
                                "meta": {
                                  "limit": 20,
                                  "page": 1,
                                  "total": 1
                                },
                                "status": {
                                  "code": 0,
                                  "message": "success"
                                }
                              }
                        }}
                    }
                }
            },
            "post":{
                "tags": ["Email"],
                "summary": "Create Email",
                "requestBody":{
                    "content": {
                        "application/json":{
                            "schema":{
                                "title": "CreateEmail",
                                "type": "object",
                                "properties": {
                                    "sender_id":{
                                        "title": "sender_id",
                                        "type": "integer",
                                        "minimum": 1
                                    },
                                    "event_id":{
                                        "title": "event_id",
                                        "type": "integer",
                                        "minimum": 1
                                    },
                                    "subject":{
                                        "title": "subject",
                                        "type": "string",
                                        "maxLength": 300
                                    },
                                    "content":{
                                        "title": "content",
                                        "type": "string"
                                    },
                                    "timestamp":{
                                        "title": "timestamp",
                                        "type": "string"
                                    }
                                    
                                },
                                "required": ["sender_id", "event_id", "content", "timestamp"]
                            },
                            "example":{
                                "sender_id": 1,
                                "event_id": 1,
                                "subject": "My Subject",
                                "content": "My Content",
                                "timestamp": "2022-03-03T10:30:30"
                            }
                        }
                    }
                },
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{},
                            "examples": {
                                "application/json":{
                                    "$ref": "#/components/examples/SuccessResponse"
                                }
                            }
                        }}
                    }
                }
            }
        },
        "/email/{id}":{
            "put":{
                "tags": ["Email"],
                "summary": "Update Email",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id",
                            "type": "integer",
                            "minimum": 1
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "requestBody":{
                    "content": {
                        "application/json":{
                            "schema":{
                                "title": "CreateEmail",
                                "type": "object",
                                "properties": {
                                    "sender_id":{
                                        "title": "sender_id",
                                        "type": "integer",
                                        "minimum": 1
                                    },
                                    "event_id":{
                                        "title": "event_id",
                                        "type": "integer",
                                        "minimum": 1
                                    },
                                    "subject":{
                                        "title": "subject",
                                        "type": "string",
                                        "maxLength": 300
                                    },
                                    "content":{
                                        "title": "content",
                                        "type": "string"
                                    },
                                    "timestamp":{
                                        "title": "timestamp",
                                        "type": "string"
                                    }
                                    
                                },
                                "required": ["sender_id", "event_id", "content", "timestamp"]
                            },
                            "example":{
                                "sender_id": 1,
                                "event_id": 1,
                                "subject": "My Subject",
                                "content": "My Content",
                                "timestamp": "2022-03-03T10:30:30"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "application/json":{
                                        "$ref": "#/components/examples/SuccessResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete":{
                "tags": ["Email"],
                "summary": "Delete Email",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id",
                            "type": "integer",
                            "minimum": 1
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "application/json":{
                                        "$ref": "#/components/examples/SuccessResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/email/address":{
            "get":{
                "tags":["Email"],
                "summary": "Get Email Address",
                "parameters": [
                    {
                        "required": false,
                        "schema": {
                            "title": "ID",
                            "type": "string",
                            "default": null
                        },
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Show the selected column, leave it empty to show all",
                        "schema": {
                            "title": "Fields",
                            "type": "string"
                        },
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "schema": {
                            "title": "Page",
                            "minimum": 1,
                            "type": "integer",
                            "default": 1
                        },
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Data limit in 1 page",
                        "schema": {
                            "title": "Limit",
                            "maximum": 100,
                            "exclusiveMinimum": false,
                            "type": "integer",
                            "default": 20
                        },
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Sort by available column",
                        "schema": {
                            "title": "Sortby",
                            "type": "string",
                            "default": "id"
                        },
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Sort the query: `asc` or `desc`",
                        "schema": {
                            "title": "SortType",
                            "type": "string",
                            "default": "asc"
                        },
                        "name": "sortType",
                        "in": "query"
                    }
                ],
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{}
                        }}
                    }
                }
            },
            "post":{
                "tags": ["Email"],
                "summary": "Create Email Address",
                "requestBody":{
                    "content": {
                        "application/json":{
                            "schema":{
                                "title": "CreateEmail",
                                "type": "object",
                                "properties": {
                                    "address":{
                                        "title": "address",
                                        "type": "string",
                                        "maximum": 100
                                    }
                                },
                                "required":["address"]
                            },
                            "example":{
                                "address":"string@gmail.com"
                            }
                        }
                    }
                },
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{}
                        }}
                    }
                }
            }
        },
        "/email/address/{id}":{
            "put":{
                "tags": ["Email"],
                "summary": "Update Email Address",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id",
                            "type": "integer",
                            "minimum": 1
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "requestBody":{
                    "content": {
                        "application/json":{
                            "schema":{
                                "title": "CreateEmail",
                                "type": "object",
                                "properties": {
                                    "address":{
                                        "title": "address",
                                        "type": "string",
                                        "maximum": 100
                                    }
                                },
                                "required":["address"]
                            },
                            "example":{
                                "address":"string@gmail.com"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "application/json":{
                                        "$ref": "#/components/examples/SuccessResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete":{
                "tags": ["Email"],
                "summary": "Delete Email Address",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id",
                            "type": "integer",
                            "minimum": 1
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "application/json":{
                                        "$ref": "#/components/examples/SuccessResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/email/save_email":{
            "post":{
                "tags":["Email"],
                "summary": "Create Email Event",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "title": "CreateEmailEvent",
                                "type": "object",
                                "properties": {
                                    "event_id":{
                                        "title": "event_id",
                                        "type": "integer",
                                        "minimum": 1
                                    },
                                    "email_subject":{
                                        "title": "email_subject",
                                        "type": "string"
                                    },
                                    "email_content":{
                                        "title": "email_content",
                                        "type": "string"
                                    },
                                    "timestamp":{
                                        "title": "timestamp",
                                        "type": "string"
                                    }
                                },
                                "required": ["event_id", "email_subject", "email_content", "timestamp"]
                            },
                            "example":{
                                "event_id": 1,
                                "email_subject": "string",
                                "email_content": "string",
                                "timestamp": "2022-02-25T20:15:10"
                            }
                        }
                    },
                    "required": true
                },
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{}
                        }}
                    }
                }
            }
        },
        "/user":{
            "get":{
                "tags":["User"],
                "summary": "Get User",
                "parameters": [
                    {
                        "required": false,
                        "schema": {
                            "title": "ID",
                            "type": "string"
                        },
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Show the selected column, leave it empty to show all",
                        "schema": {
                            "title": "Fields",
                            "type": "string"
                        },
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "schema": {
                            "title": "Page",
                            "minimum": 1,
                            "type": "integer",
                            "default": 1
                        },
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Data limit in 1 page",
                        "schema": {
                            "title": "Limit",
                            "maximum": 100,
                            "exclusiveMinimum": false,
                            "type": "integer",
                            "default": 20
                        },
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Sort by available column",
                        "schema": {
                            "title": "Sortby",
                            "type": "string",
                            "default": "id"
                        },
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Sort the query: `asc` or `desc`",
                        "schema": {
                            "title": "SortType",
                            "type": "string",
                            "enum": ["asc","desc"],
                            "default": "asc",
                            "required": ["SortType"]
                        },                        
                        "name": "sortType",
                        "in": "query"
                    }
                ],
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{}
                        }}
                    }
                }
            },
            "post":{
                "tags": ["User"],
                "summary": "Create User",
                "requestBody":{
                    "content": {
                        "application/json":{
                            "schema":{
                                "title": "CreateUser",
                                "type": "object",
                                "properties": {
                                    "email":{
                                        "title": "email",
                                        "type": "string",
                                        "maxLength": 100
                                    },
                                    "password":{
                                        "title": "password",
                                        "type": "string",
                                        "maxLength": 100
                                    }
                                },
                                "required": true
                            },
                            "example":{
                                "email": "string@gmail.com",
                                "password": "string"
                            }
                        }
                    }
                },
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{},
                            "examples": {
                                "application/json":{
                                    "$ref": "#/components/examples/SuccessResponse"
                                }
                            }
                        }}
                    }
                }
            }
        },
        "/user/{id}":{
            "put":{
                "tags": ["User"],
                "summary": "Update User",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id",
                            "type": "integer",
                            "minimum": 1
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "requestBody":{
                    "content": {
                        "application/json":{
                            "schema":{
                                "title": "CreateUser",
                                "type": "object",
                                "properties": {
                                    "email":{
                                        "title": "email",
                                        "type": "string",
                                        "maxLength": 100
                                    },
                                    "password":{
                                        "title": "password",
                                        "type": "string",
                                        "maxLength": 100
                                    }
                                }
                            },
                            "example":{
                                "email": "string@gmail.com",
                                "password": "string"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "application/json":{
                                        "$ref": "#/components/examples/SuccessResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete":{
                "tags": ["User"],
                "summary": "Delete User",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id",
                            "type": "integer",
                            "minimum": 1
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "application/json":{
                                        "$ref": "#/components/examples/SuccessResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/event":{
            "get":{
                "tags":["Event"],
                "summary": "Get Event",
                "parameters": [
                    {
                        "required": false,
                        "schema": {
                            "title": "ID",
                            "type": "string"
                        },
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Show the selected column, leave it empty to show all",
                        "schema": {
                            "title": "Fields",
                            "type": "string"
                        },
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "schema": {
                            "title": "Page",
                            "minimum": 1,
                            "type": "integer",
                            "default": 1
                        },
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Data limit in 1 page",
                        "schema": {
                            "title": "Limit",
                            "maximum": 100,
                            "exclusiveMinimum": false,
                            "type": "integer",
                            "default": 20
                        },
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Sort by available column",
                        "schema": {
                            "title": "Sortby",
                            "type": "string",
                            "default": "id"
                        },
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Sort the query: `asc` or `desc`",
                        "schema": {
                            "title": "SortType",
                            "type": "string",
                            "default": "asc"
                        },
                        "name": "sortType",
                        "in": "query"
                    }
                ],
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{}
                        }}
                    }
                }
            },
            "post":{
                "tags": ["Event"],
                "summary": "Create Event",
                "requestBody":{
                    "content": {
                        "application/json":{
                            "schema":{
                                "title": "CreateEvent",
                                "type": "object",
                                "properties": {
                                    "owner_id":{
                                        "title": "owner_id",
                                        "type": "integer",
                                        "minimum": 1
                                    },
                                    "name":{
                                        "title": "name",
                                        "type": "string",
                                        "maxLength": 100
                                    }
                                },
                                "required": ["owner_id", "name"]
                            },
                            "example":{
                                "owner_id": 1,
                                "name": "My Event"
                            }
                        }
                    }
                },
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{},
                            "examples": {
                                "application/json":{
                                    "$ref": "#/components/examples/SuccessResponse"
                                }
                            }
                        }}
                    }
                }
            }
        },
        "/event/{id}":{
            "put":{
                "tags": ["Event"],
                "summary": "Update Event",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id",
                            "type": "integer",
                            "minimum": 1
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "requestBody":{
                    "content": {
                        "application/json":{
                            "schema":{
                                "title": "CreateEvent",
                                "type": "object",
                                "properties": {
                                    "owner_id":{
                                        "title": "owner_id",
                                        "type": "integer",
                                        "minimum": 1
                                    },
                                    "name":{
                                        "title": "name",
                                        "type": "string",
                                        "maxLength": 100
                                    }
                                }
                            },
                            "example":{
                                "owner_id": 1,
                                "name": "My Event"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "application/json":{
                                        "$ref": "#/components/examples/SuccessResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete":{
                "tags": ["Event"],
                "summary": "Delete Event",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id",
                            "type": "integer",
                            "minimum": 1
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "application/json":{
                                        "$ref": "#/components/examples/SuccessResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/event/{event_id}/participant":{
            "get":{
                "tags":["Event"],
                "summary": "Get Event",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "event_id",
                            "type": "integer"
                        },
                        "name": "event_id",
                        "in": "path"
                    },
                    {
                        "required": false,
                        "schema": {
                            "title": "ID",
                            "type": "string"
                        },
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Show the selected column, leave it empty to show all",
                        "schema": {
                            "title": "Fields",
                            "type": "string"
                        },
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "schema": {
                            "title": "Page",
                            "minimum": 1,
                            "type": "integer",
                            "default": 1
                        },
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Data limit in 1 page",
                        "schema": {
                            "title": "Limit",
                            "maximum": 100,
                            "exclusiveMinimum": false,
                            "type": "integer",
                            "default": 20
                        },
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Sort by available column",
                        "schema": {
                            "title": "Sortby",
                            "type": "string",
                            "default": "id"
                        },
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "required": false,
                        "description": "Sort the query: `asc` or `desc`",
                        "schema": {
                            "title": "SortType",
                            "type": "string",
                            "default": "asc"
                        },
                        "name": "sortType",
                        "in": "query"
                    }
                ],
                "responses":{
                    "200":{
                        "description": "Succesfull Response",
                        "content":{"application/json":{
                            "schema":{}
                        }}
                    }
                }
            },
            "put":{
                "tags": ["Event"],
                "summary": "Update Event Participant",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "eventid",
                            "type": "integer",
                            "minimum": 1
                        },
                        "name": "event_id",
                        "in": "path"
                    }
                ],
                "requestBody":{
                    "content": {
                        "application/json":{
                            "schema":{
                                "title": "EditParticipant",
                                "type": "object",
                                "properties": {
                                    "address":{
                                        "title": "address",
                                        "type": "string",
                                        "maxLength": 100
                                    }
                                }
                            },
                            "example":{
                                "address": "string@gmail.com"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "application/json":{
                                        "$ref": "#/components/examples/SuccessResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/event/participant/{participant_id}":{
            "delete":{
                "tags": ["Event"],
                "summary": "Delete Event",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "participant_id",
                            "type": "integer",
                            "minimum": 1
                        },
                        "name": "participant_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "application/json":{
                                        "$ref": "#/components/examples/SuccessResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "examples": {
            "SuccessResponse":{
                "data": {},
                "meta": {},
                "status": {
                    "code": 100,
                    "message": "success"
                }
            }
        }
    }
}